run:
  timeout: 3m
  modules-download-mode: readonly

issues:
  exclude-dirs:
    - sample

linters:
  # enable additional linters, that are disabled by default
  enable:
    - contextcheck
    - godot
    - gofmt
    - goimports
    - misspell
    - whitespace

