linters-settings:
  misspell:
    locale: UK
    ignore-words:
      - standardize  # hujson library uses US spelling
linters:
  enable:
    - contextcheck
    - errcheck
    - godot
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused
    - whitespace
  disable-all: true
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
run:
  timeout: 5m
