version: "2"
linters:
  default: none
  enable:
    - contextcheck
    - errcheck
    - godot
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused
    - whitespace
  settings:
    misspell:
      locale: UK
      ignore-rules:
        - standardize  # hujson library uses US spelling
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
