repos:
    - repo: https://github.com/dnephin/pre-commit-golang
      rev: v0.5.0

      hooks:
        - id: go-fmt
        - id: go-vet
        - id: go-imports
        - id: golangci-lint
        - id: go-critic
        - id: go-build
        - id: go-mod-tidy


